services:
  - type: web
    name: emotify-backend
    runtime: python
    rootDir: emotionDetection
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
